using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static ShaderContractGenerator.AttributeValues;

namespace ShaderContractGenerator;

/// <summary>Emits shader-owned immutable declarations and typed accessors without runtime discovery.</summary>
internal static class DeclarationEmitter
{
    #region Owners and catalog
    /// <summary>Emits an owner shell offline or a partial implementation beside the actual runtime class.</summary>
    public static string Owner(OwnerDeclaration owner, bool offline)
    {
        var text = new StringBuilder("// <auto-generated/>\n#nullable enable\nusing VanillaGraphicsExpanded.Rendering.Contracts;\n");
        if (!owner.Symbol.ContainingNamespace.IsGlobalNamespace) text.Append("namespace ").Append(owner.Symbol.ContainingNamespace.ToDisplayString()).Append(";\n");
        text.Append("/// <summary>Generated shader declarations.</summary>\n")
            .Append(owner.Symbol.DeclaredAccessibility == Accessibility.Public ? "public " : "internal ")
            .Append(owner.Symbol.IsStatic ? "static " : "")
            .Append("partial class ").Append(owner.Symbol.Name).Append("\n{\n#region Generated declarations\n");
        foreach (var option in owner.Options.Values.OrderBy(o => o.Property.Name, StringComparer.Ordinal))
        {
            text.Append("/// <summary>Initializes this key independently of other static owner members.</summary>\nprivate static class __").Append(option.KeyName).Append("Storage { internal static readonly ShaderOption<").Append(option.TypeName).Append("> Value = ").Append(option.Initializer).Append("; }\n");
            string access = option.Shared ? AccessibilityText(option.Property.DeclaredAccessibility) : "internal";
            text.Append("/// <summary>Immutable typed option key.</summary>\n").Append(access).Append(" static ")
                .Append(option.Shared && !offline ? "partial " : "")
                .Append("ShaderOption<").Append(option.TypeName).Append("> ").Append(option.KeyName).Append(" { get => __").Append(option.KeyName).Append("Storage.Value; }\n");
        }
        foreach (var group in owner.Groups.OrderBy(p => p.Key, StringComparer.Ordinal))
            text.Append("internal static ShaderOptionGroup ").Append(group.Key).Append(" { get; } = ").Append(group.Value.Expression).Append(";\n");
        foreach (var program in owner.Programs.OrderBy(p => p.Member, StringComparer.Ordinal))
            text.Append("internal static GpuShaderContract ").Append(program.Member).Append(" { get; } = ").Append(program.Expression).Append(";\n");
        if (owner.Programs.Count > 1)
            text.Append("internal static System.Collections.Generic.IReadOnlyList<GpuShaderContract> Contracts { get; } = System.Array.AsReadOnly(new GpuShaderContract[] { ").Append(string.Join(", ", owner.Programs.OrderBy(p => p.Member, StringComparer.Ordinal).Select(p => p.Member))).Append(" });\n");
        if (!offline)
            foreach (var option in owner.Options.Values.Where(o => !o.Shared).OrderBy(o => o.Property.Name, StringComparer.Ordinal))
            {
                var syntax = (PropertyDeclarationSyntax)option.Property.DeclaringSyntaxReferences[0].GetSyntax();
                text.Append("/// <summary>Validates and updates the selected shader option.</summary>\n")
                    .Append(string.Join(" ", syntax.Modifiers.Select(m => m.Text))).Append(' ').Append(option.TypeName).Append(' ').Append(option.Property.Name).Append(" { ");
                foreach (var accessor in syntax.AccessorList!.Accessors)
                    text.Append(string.Join(" ", accessor.Modifiers.Select(m => m.Text))).Append(' ').Append(accessor.Keyword.Text).Append(" => ")
                        .Append(accessor.IsKind(SyntaxKind.GetAccessorDeclaration) ? $"GetShaderOption({option.KeyName})" : $"SetShaderOptions(options => options.Set({option.KeyName}, value))").Append("; ");
                text.Append("}\n");
            }
        text.Append("#endregion\n}\n");
        return text.ToString();
    }
    /// <summary>Generates deterministic scope lookup using direct references to declared owners.</summary>
    public static string Catalog(IEnumerable<OwnerDeclaration> owners)
    {
        var ordered = owners.OrderBy(o => o.Name, StringComparer.Ordinal).ToArray();
        var programs = ordered.SelectMany(o => o.Programs.Select(p => (Owner: o, Program: p))).ToArray();
        var text = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace VanillaGraphicsExpanded.Rendering.Contracts;\n/// <summary>Generated references to shader-owned contracts.</summary>\ninternal static class GeneratedShaderCatalog\n{\n#region Scope lookup\n/// <summary>Returns declarations belonging to one explicit compilation scope.</summary>\ninternal static System.Collections.Generic.IReadOnlyList<GpuShaderContract> Programs(string scope = \"production\") => scope switch\n{\n");
        foreach (var scope in programs.GroupBy(p => p.Program.Scope).OrderBy(g => g.Key, StringComparer.Ordinal))
            text.Append(Quote(scope.Key)).Append(" => System.Array.AsReadOnly(new GpuShaderContract[] { ")
                .Append(string.Join(", ", scope.OrderBy(p => p.Program.Model.Identity, StringComparer.Ordinal).Select(p => p.Owner.Name + "." + p.Program.Member))).Append(" }),\n");
        text.Append("_ => System.Array.Empty<GpuShaderContract>()\n};\n#endregion\n}\n");
        return text.ToString();
    }
    /// <summary>Copies only the referenced enum's semantic names and constants into offline build input.</summary>
    public static string Enum(INamedTypeSymbol type)
    {
        string members = string.Join(", ", type.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue)
            .Select(f => "@" + f.Name + " = " + System.Convert.ToString(f.ConstantValue, System.Globalization.CultureInfo.InvariantCulture) +
                (type.EnumUnderlyingType!.SpecialType == SpecialType.System_UInt32 ? "u" : "")));
        string scope = type.ContainingNamespace.IsGlobalNamespace ? "" : "namespace " + type.ContainingNamespace.ToDisplayString() + ";\n";
        return "// <auto-generated/>\n" + scope + "/// <summary>Shader option enum shared with runtime declarations.</summary>\n" +
            AccessibilityText(type.DeclaredAccessibility) + " enum " + type.Name + " : " + type.EnumUnderlyingType!.ToDisplayString() + " { " + members + " }\n";
    }
    /// <summary>Formats accessibility without relying on enum spelling for compound modifiers.</summary>
    private static string AccessibilityText(Accessibility value) => value switch
    {
        Accessibility.Public => "public", Accessibility.Private => "private", Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal", Accessibility.ProtectedAndInternal => "private protected", _ => "internal"
    };
    #endregion
}


