using VanillaGraphicsExpanded.Rendering.Contracts;

namespace VanillaGraphicsExpanded.LumOn;

/// <summary>Declares an independently compiled executable for every fullscreen debug view.</summary>
[ShaderProgram("ProbeGridContract", "lumon_debug_view_probe_grid", 2)]
[ShaderStage("ProbeGridContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeGridContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_grid.fsh")]
[ShaderAcceptGroup("ProbeGridContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeGridContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeDepthContract", "lumon_debug_view_probe_depth", 2)]
[ShaderStage("ProbeDepthContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeDepthContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_depth.fsh")]
[ShaderAcceptGroup("ProbeDepthContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeDepthContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeNormalContract", "lumon_debug_view_probe_normal", 2)]
[ShaderStage("ProbeNormalContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeNormalContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_normal.fsh")]
[ShaderAcceptGroup("ProbeNormalContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeNormalContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("SceneDepthContract", "lumon_debug_view_scene_depth", 2)]
[ShaderStage("SceneDepthContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("SceneDepthContract", ShaderStageKind.Fragment, "lumon_debug_view_scene_depth.fsh")]
[ShaderAcceptGroup("SceneDepthContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("SceneDepthContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("SceneNormalContract", "lumon_debug_view_scene_normal", 2)]
[ShaderStage("SceneNormalContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("SceneNormalContract", ShaderStageKind.Fragment, "lumon_debug_view_scene_normal.fsh")]
[ShaderAcceptGroup("SceneNormalContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("SceneNormalContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("TemporalWeightContract", "lumon_debug_view_temporal_weight", 2)]
[ShaderStage("TemporalWeightContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("TemporalWeightContract", ShaderStageKind.Fragment, "lumon_debug_view_temporal_weight.fsh")]
[ShaderAcceptGroup("TemporalWeightContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("TemporalWeightContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("TemporalRejectionContract", "lumon_debug_view_temporal_rejection", 2)]
[ShaderStage("TemporalRejectionContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("TemporalRejectionContract", ShaderStageKind.Fragment, "lumon_debug_view_temporal_rejection.fsh")]
[ShaderAcceptGroup("TemporalRejectionContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("TemporalRejectionContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ShCoefficientsContract", "lumon_debug_view_sh_coefficients", 2)]
[ShaderStage("ShCoefficientsContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ShCoefficientsContract", ShaderStageKind.Fragment, "lumon_debug_view_sh_coefficients.fsh")]
[ShaderAcceptGroup("ShCoefficientsContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ShCoefficientsContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("InterpolationWeightsContract", "lumon_debug_view_interpolation_weights", 2)]
[ShaderStage("InterpolationWeightsContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("InterpolationWeightsContract", ShaderStageKind.Fragment, "lumon_debug_view_interpolation_weights.fsh")]
[ShaderAcceptGroup("InterpolationWeightsContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("InterpolationWeightsContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("RadianceOverlayContract", "lumon_debug_view_radiance_overlay", 2)]
[ShaderStage("RadianceOverlayContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("RadianceOverlayContract", ShaderStageKind.Fragment, "lumon_debug_view_radiance_overlay.fsh")]
[ShaderAcceptGroup("RadianceOverlayContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("RadianceOverlayContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("GatherWeightContract", "lumon_debug_view_gather_weight", 2)]
[ShaderStage("GatherWeightContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("GatherWeightContract", ShaderStageKind.Fragment, "lumon_debug_view_gather_weight.fsh")]
[ShaderAcceptGroup("GatherWeightContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("GatherWeightContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasMetaConfidenceContract", "lumon_debug_view_probe_atlas_meta_confidence", 2)]
[ShaderStage("ProbeAtlasMetaConfidenceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasMetaConfidenceContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_meta_confidence.fsh")]
[ShaderAcceptGroup("ProbeAtlasMetaConfidenceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasMetaConfidenceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasTemporalAlphaContract", "lumon_debug_view_probe_atlas_temporal_alpha", 2)]
[ShaderStage("ProbeAtlasTemporalAlphaContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasTemporalAlphaContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_temporal_alpha.fsh")]
[ShaderAcceptGroup("ProbeAtlasTemporalAlphaContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasTemporalAlphaContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasMetaFlagsContract", "lumon_debug_view_probe_atlas_meta_flags", 2)]
[ShaderStage("ProbeAtlasMetaFlagsContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasMetaFlagsContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_meta_flags.fsh")]
[ShaderAcceptGroup("ProbeAtlasMetaFlagsContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasMetaFlagsContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasFilteredRadianceContract", "lumon_debug_view_probe_atlas_filtered_radiance", 2)]
[ShaderStage("ProbeAtlasFilteredRadianceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasFilteredRadianceContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_filtered_radiance.fsh")]
[ShaderAcceptGroup("ProbeAtlasFilteredRadianceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasFilteredRadianceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasFilterDeltaContract", "lumon_debug_view_probe_atlas_filter_delta", 2)]
[ShaderStage("ProbeAtlasFilterDeltaContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasFilterDeltaContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_filter_delta.fsh")]
[ShaderAcceptGroup("ProbeAtlasFilterDeltaContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasFilterDeltaContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasGatherInputSourceContract", "lumon_debug_view_probe_atlas_gather_input_source", 2)]
[ShaderStage("ProbeAtlasGatherInputSourceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasGatherInputSourceContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_gather_input_source.fsh")]
[ShaderAcceptGroup("ProbeAtlasGatherInputSourceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasGatherInputSourceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("CompositeAOContract", "lumon_debug_view_composite_ao", 16)]
[ShaderStage("CompositeAOContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("CompositeAOContract", ShaderStageKind.Fragment, "lumon_debug_view_composite_ao.fsh")]
[ShaderAcceptGroup("CompositeAOContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("CompositeAOContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("CompositeAOContract", typeof(LumOnShaderGroups), "Composite")]
[ShaderAcceptGroup("CompositeAOContract", typeof(LumOnShaderGroups), "Ao")]
[ShaderUse("CompositeAOContract", ShaderStageKind.Fragment, nameof(EnableAO))]
[ShaderUse("CompositeAOContract", ShaderStageKind.Fragment, nameof(EnablePbrComposite))]
[ShaderUse("CompositeAOContract", ShaderStageKind.Fragment, nameof(EnableShortRangeAo))]
[ShaderProgram("CompositeIndirectDiffuseContract", "lumon_debug_view_composite_indirect_diffuse", 16)]
[ShaderStage("CompositeIndirectDiffuseContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("CompositeIndirectDiffuseContract", ShaderStageKind.Fragment, "lumon_debug_view_composite_indirect_diffuse.fsh")]
[ShaderAcceptGroup("CompositeIndirectDiffuseContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("CompositeIndirectDiffuseContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("CompositeIndirectDiffuseContract", typeof(LumOnShaderGroups), "Composite")]
[ShaderAcceptGroup("CompositeIndirectDiffuseContract", typeof(LumOnShaderGroups), "Ao")]
[ShaderUse("CompositeIndirectDiffuseContract", ShaderStageKind.Fragment, nameof(EnableAO))]
[ShaderUse("CompositeIndirectDiffuseContract", ShaderStageKind.Fragment, nameof(EnablePbrComposite))]
[ShaderUse("CompositeIndirectDiffuseContract", ShaderStageKind.Fragment, nameof(EnableShortRangeAo))]
[ShaderProgram("CompositeIndirectSpecularContract", "lumon_debug_view_composite_indirect_specular", 16)]
[ShaderStage("CompositeIndirectSpecularContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("CompositeIndirectSpecularContract", ShaderStageKind.Fragment, "lumon_debug_view_composite_indirect_specular.fsh")]
[ShaderAcceptGroup("CompositeIndirectSpecularContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("CompositeIndirectSpecularContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("CompositeIndirectSpecularContract", typeof(LumOnShaderGroups), "Composite")]
[ShaderAcceptGroup("CompositeIndirectSpecularContract", typeof(LumOnShaderGroups), "Ao")]
[ShaderUse("CompositeIndirectSpecularContract", ShaderStageKind.Fragment, nameof(EnableAO))]
[ShaderUse("CompositeIndirectSpecularContract", ShaderStageKind.Fragment, nameof(EnablePbrComposite))]
[ShaderUse("CompositeIndirectSpecularContract", ShaderStageKind.Fragment, nameof(EnableShortRangeAo))]
[ShaderProgram("CompositeMaterialContract", "lumon_debug_view_composite_material", 16)]
[ShaderStage("CompositeMaterialContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("CompositeMaterialContract", ShaderStageKind.Fragment, "lumon_debug_view_composite_material.fsh")]
[ShaderAcceptGroup("CompositeMaterialContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("CompositeMaterialContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("CompositeMaterialContract", typeof(LumOnShaderGroups), "Composite")]
[ShaderAcceptGroup("CompositeMaterialContract", typeof(LumOnShaderGroups), "Ao")]
[ShaderUse("CompositeMaterialContract", ShaderStageKind.Fragment, nameof(EnableAO))]
[ShaderUse("CompositeMaterialContract", ShaderStageKind.Fragment, nameof(EnablePbrComposite))]
[ShaderUse("CompositeMaterialContract", ShaderStageKind.Fragment, nameof(EnableShortRangeAo))]
[ShaderProgram("DirectDiffuseContract", "lumon_debug_view_direct_diffuse", 2)]
[ShaderStage("DirectDiffuseContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("DirectDiffuseContract", ShaderStageKind.Fragment, "lumon_debug_view_direct_diffuse.fsh")]
[ShaderAcceptGroup("DirectDiffuseContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("DirectDiffuseContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("DirectSpecularContract", "lumon_debug_view_direct_specular", 2)]
[ShaderStage("DirectSpecularContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("DirectSpecularContract", ShaderStageKind.Fragment, "lumon_debug_view_direct_specular.fsh")]
[ShaderAcceptGroup("DirectSpecularContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("DirectSpecularContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("DirectEmissiveContract", "lumon_debug_view_direct_emissive", 2)]
[ShaderStage("DirectEmissiveContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("DirectEmissiveContract", ShaderStageKind.Fragment, "lumon_debug_view_direct_emissive.fsh")]
[ShaderAcceptGroup("DirectEmissiveContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("DirectEmissiveContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("DirectTotalContract", "lumon_debug_view_direct_total", 2)]
[ShaderStage("DirectTotalContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("DirectTotalContract", ShaderStageKind.Fragment, "lumon_debug_view_direct_total.fsh")]
[ShaderAcceptGroup("DirectTotalContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("DirectTotalContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("VelocityMagnitudeContract", "lumon_debug_view_velocity_magnitude", 2)]
[ShaderStage("VelocityMagnitudeContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("VelocityMagnitudeContract", ShaderStageKind.Fragment, "lumon_debug_view_velocity_magnitude.fsh")]
[ShaderAcceptGroup("VelocityMagnitudeContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("VelocityMagnitudeContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("VelocityValidityContract", "lumon_debug_view_velocity_validity", 2)]
[ShaderStage("VelocityValidityContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("VelocityValidityContract", ShaderStageKind.Fragment, "lumon_debug_view_velocity_validity.fsh")]
[ShaderAcceptGroup("VelocityValidityContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("VelocityValidityContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("VelocityPrevUvContract", "lumon_debug_view_velocity_prev_uv", 2)]
[ShaderStage("VelocityPrevUvContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("VelocityPrevUvContract", ShaderStageKind.Fragment, "lumon_debug_view_velocity_prev_uv.fsh")]
[ShaderAcceptGroup("VelocityPrevUvContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("VelocityPrevUvContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("MaterialBandsContract", "lumon_debug_view_material_bands", 2)]
[ShaderStage("MaterialBandsContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("MaterialBandsContract", ShaderStageKind.Fragment, "lumon_debug_view_material_bands.fsh")]
[ShaderAcceptGroup("MaterialBandsContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("MaterialBandsContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("WorldProbeIrradianceCombinedContract", "lumon_debug_view_world_probe_irradiance_combined", 4)]
[ShaderStage("WorldProbeIrradianceCombinedContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeIrradianceCombinedContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_irradiance_combined.fsh")]
[ShaderAcceptGroup("WorldProbeIrradianceCombinedContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeIrradianceCombinedContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeIrradianceCombinedContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeIrradianceCombinedContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeIrradianceCombinedContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeIrradianceCombinedContract", ShaderStageKind.Fragment, nameof(WorldProbeDiffuseStride), SpecializationId = 15, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeIrradianceCombinedContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeIrradianceCombinedContract", ShaderStageKind.Fragment, nameof(WorldProbeOctahedralSize), SpecializationId = 13, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeIrradianceCombinedContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeIrradianceCombinedContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("WorldProbeIrradianceLevelContract", "lumon_debug_view_world_probe_irradiance_level", 4)]
[ShaderStage("WorldProbeIrradianceLevelContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeIrradianceLevelContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_irradiance_level.fsh")]
[ShaderAcceptGroup("WorldProbeIrradianceLevelContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeIrradianceLevelContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeIrradianceLevelContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeIrradianceLevelContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeIrradianceLevelContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeIrradianceLevelContract", ShaderStageKind.Fragment, nameof(WorldProbeDiffuseStride), SpecializationId = 15, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeIrradianceLevelContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeIrradianceLevelContract", ShaderStageKind.Fragment, nameof(WorldProbeOctahedralSize), SpecializationId = 13, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeIrradianceLevelContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeIrradianceLevelContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("WorldProbeConfidenceContract", "lumon_debug_view_world_probe_confidence", 4)]
[ShaderStage("WorldProbeConfidenceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeConfidenceContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_confidence.fsh")]
[ShaderAcceptGroup("WorldProbeConfidenceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeConfidenceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeConfidenceContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeConfidenceContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeConfidenceContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeConfidenceContract", ShaderStageKind.Fragment, nameof(WorldProbeDiffuseStride), SpecializationId = 15, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeConfidenceContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeConfidenceContract", ShaderStageKind.Fragment, nameof(WorldProbeOctahedralSize), SpecializationId = 13, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeConfidenceContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeConfidenceContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("WorldProbeShortRangeAoDirectionContract", "lumon_debug_view_world_probe_short_range_ao_direction", 4)]
[ShaderStage("WorldProbeShortRangeAoDirectionContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeShortRangeAoDirectionContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_short_range_ao_direction.fsh")]
[ShaderAcceptGroup("WorldProbeShortRangeAoDirectionContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeShortRangeAoDirectionContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeShortRangeAoDirectionContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeShortRangeAoDirectionContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeShortRangeAoDirectionContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeShortRangeAoDirectionContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeShortRangeAoDirectionContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeShortRangeAoDirectionContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("WorldProbeShortRangeAoConfidenceContract", "lumon_debug_view_world_probe_short_range_ao_confidence", 4)]
[ShaderStage("WorldProbeShortRangeAoConfidenceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeShortRangeAoConfidenceContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_short_range_ao_confidence.fsh")]
[ShaderAcceptGroup("WorldProbeShortRangeAoConfidenceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeShortRangeAoConfidenceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeShortRangeAoConfidenceContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeShortRangeAoConfidenceContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeShortRangeAoConfidenceContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeShortRangeAoConfidenceContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeShortRangeAoConfidenceContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeShortRangeAoConfidenceContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("WorldProbeHitDistanceContract", "lumon_debug_view_world_probe_hit_distance", 4)]
[ShaderStage("WorldProbeHitDistanceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeHitDistanceContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_hit_distance.fsh")]
[ShaderAcceptGroup("WorldProbeHitDistanceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeHitDistanceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeHitDistanceContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeHitDistanceContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeHitDistanceContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeHitDistanceContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeHitDistanceContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeHitDistanceContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("WorldProbeMetaFlagsHeatmapContract", "lumon_debug_view_world_probe_meta_flags_heatmap", 4)]
[ShaderStage("WorldProbeMetaFlagsHeatmapContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeMetaFlagsHeatmapContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_meta_flags_heatmap.fsh")]
[ShaderAcceptGroup("WorldProbeMetaFlagsHeatmapContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeMetaFlagsHeatmapContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeMetaFlagsHeatmapContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeMetaFlagsHeatmapContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeMetaFlagsHeatmapContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeMetaFlagsHeatmapContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeMetaFlagsHeatmapContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeMetaFlagsHeatmapContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("WorldProbeBlendWeightsContract", "lumon_debug_view_world_probe_blend_weights", 4)]
[ShaderStage("WorldProbeBlendWeightsContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeBlendWeightsContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_blend_weights.fsh")]
[ShaderAcceptGroup("WorldProbeBlendWeightsContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeBlendWeightsContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeBlendWeightsContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeBlendWeightsContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeBlendWeightsContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeBlendWeightsContract", ShaderStageKind.Fragment, nameof(WorldProbeDiffuseStride), SpecializationId = 15, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeBlendWeightsContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeBlendWeightsContract", ShaderStageKind.Fragment, nameof(WorldProbeOctahedralSize), SpecializationId = 13, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeBlendWeightsContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeBlendWeightsContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("WorldProbeCrossLevelBlendContract", "lumon_debug_view_world_probe_cross_level_blend", 4)]
[ShaderStage("WorldProbeCrossLevelBlendContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeCrossLevelBlendContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_cross_level_blend.fsh")]
[ShaderAcceptGroup("WorldProbeCrossLevelBlendContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeCrossLevelBlendContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeCrossLevelBlendContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeCrossLevelBlendContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeCrossLevelBlendContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeCrossLevelBlendContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeCrossLevelBlendContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeCrossLevelBlendContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("PomMetricsContract", "lumon_debug_view_pom_metrics", 2)]
[ShaderStage("PomMetricsContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("PomMetricsContract", ShaderStageKind.Fragment, "lumon_debug_view_pom_metrics.fsh")]
[ShaderAcceptGroup("PomMetricsContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("PomMetricsContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("WorldProbeRawConfidencesContract", "lumon_debug_view_world_probe_raw_confidences", 4)]
[ShaderStage("WorldProbeRawConfidencesContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeRawConfidencesContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_raw_confidences.fsh")]
[ShaderAcceptGroup("WorldProbeRawConfidencesContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeRawConfidencesContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeRawConfidencesContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeRawConfidencesContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeRawConfidencesContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeRawConfidencesContract", ShaderStageKind.Fragment, nameof(WorldProbeDiffuseStride), SpecializationId = 15, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeRawConfidencesContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeRawConfidencesContract", ShaderStageKind.Fragment, nameof(WorldProbeOctahedralSize), SpecializationId = 13, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeRawConfidencesContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeRawConfidencesContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("WorldProbeLightingEffectContract", "lumon_debug_view_world_probe_lighting_effect", 2)]
[ShaderStage("WorldProbeLightingEffectContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeLightingEffectContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_lighting_effect.fsh")]
[ShaderAcceptGroup("WorldProbeLightingEffectContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeLightingEffectContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("WorldProbeSuppressedLightingContract", "lumon_debug_view_world_probe_suppressed_lighting", 2)]
[ShaderStage("WorldProbeSuppressedLightingContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeSuppressedLightingContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_suppressed_lighting.fsh")]
[ShaderAcceptGroup("WorldProbeSuppressedLightingContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeSuppressedLightingContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasCurrentRadianceContract", "lumon_debug_view_probe_atlas_current_radiance", 2)]
[ShaderStage("ProbeAtlasCurrentRadianceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasCurrentRadianceContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_current_radiance.fsh")]
[ShaderAcceptGroup("ProbeAtlasCurrentRadianceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasCurrentRadianceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasGatherInputRadianceContract", "lumon_debug_view_probe_atlas_gather_input_radiance", 2)]
[ShaderStage("ProbeAtlasGatherInputRadianceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasGatherInputRadianceContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_gather_input_radiance.fsh")]
[ShaderAcceptGroup("ProbeAtlasGatherInputRadianceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasGatherInputRadianceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasHitDistanceContract", "lumon_debug_view_probe_atlas_hit_distance", 2)]
[ShaderStage("ProbeAtlasHitDistanceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasHitDistanceContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_hit_distance.fsh")]
[ShaderAcceptGroup("ProbeAtlasHitDistanceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasHitDistanceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasTraceRadianceContract", "lumon_debug_view_probe_atlas_trace_radiance", 2)]
[ShaderStage("ProbeAtlasTraceRadianceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasTraceRadianceContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_trace_radiance.fsh")]
[ShaderAcceptGroup("ProbeAtlasTraceRadianceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasTraceRadianceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasTemporalRejectionContract", "lumon_debug_view_probe_atlas_temporal_rejection", 2)]
[ShaderStage("ProbeAtlasTemporalRejectionContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasTemporalRejectionContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_temporal_rejection.fsh")]
[ShaderAcceptGroup("ProbeAtlasTemporalRejectionContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasTemporalRejectionContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbeAtlasPisTraceMaskContract", "lumon_debug_view_probe_atlas_pis_trace_mask", 2)]
[ShaderStage("ProbeAtlasPisTraceMaskContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasPisTraceMaskContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_pis_trace_mask.fsh")]
[ShaderAcceptGroup("ProbeAtlasPisTraceMaskContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasPisTraceMaskContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("ProbePisEnergyContract", "lumon_debug_view_probe_pis_energy", 2)]
[ShaderStage("ProbePisEnergyContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbePisEnergyContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_pis_energy.fsh")]
[ShaderAcceptGroup("ProbePisEnergyContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbePisEnergyContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonScenePageReadyContract", "lumon_debug_view_lumon_scene_page_ready", 2)]
[ShaderStage("LumonScenePageReadyContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonScenePageReadyContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_page_ready.fsh")]
[ShaderAcceptGroup("LumonScenePageReadyContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonScenePageReadyContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonScenePatchUvContract", "lumon_debug_view_lumon_scene_patch_uv", 2)]
[ShaderStage("LumonScenePatchUvContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonScenePatchUvContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_patch_uv.fsh")]
[ShaderAcceptGroup("LumonScenePatchUvContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonScenePatchUvContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonSceneIrradianceContract", "lumon_debug_view_lumon_scene_irradiance", 2)]
[ShaderStage("LumonSceneIrradianceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonSceneIrradianceContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_irradiance.fsh")]
[ShaderAcceptGroup("LumonSceneIrradianceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonSceneIrradianceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("TraceSceneBoundsL0Contract", "lumon_debug_view_trace_scene_bounds_l0", 2)]
[ShaderStage("TraceSceneBoundsL0Contract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("TraceSceneBoundsL0Contract", ShaderStageKind.Fragment, "lumon_debug_view_trace_scene_bounds_l0.fsh")]
[ShaderAcceptGroup("TraceSceneBoundsL0Contract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("TraceSceneBoundsL0Contract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("TraceSceneOccupancyL0Contract", "lumon_debug_view_trace_scene_occupancy_l0", 2)]
[ShaderStage("TraceSceneOccupancyL0Contract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("TraceSceneOccupancyL0Contract", ShaderStageKind.Fragment, "lumon_debug_view_trace_scene_occupancy_l0.fsh")]
[ShaderAcceptGroup("TraceSceneOccupancyL0Contract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("TraceSceneOccupancyL0Contract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("TraceScenePayloadL0Contract", "lumon_debug_view_trace_scene_payload_l0", 2)]
[ShaderStage("TraceScenePayloadL0Contract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("TraceScenePayloadL0Contract", ShaderStageKind.Fragment, "lumon_debug_view_trace_scene_payload_l0.fsh")]
[ShaderAcceptGroup("TraceScenePayloadL0Contract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("TraceScenePayloadL0Contract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumOnScenesOverviewContract", "lumon_debug_view_lum_on_scenes_overview", 2)]
[ShaderStage("LumOnScenesOverviewContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumOnScenesOverviewContract", ShaderStageKind.Fragment, "lumon_debug_view_lum_on_scenes_overview.fsh")]
[ShaderAcceptGroup("LumOnScenesOverviewContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumOnScenesOverviewContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonSceneChunkSlotContract", "lumon_debug_view_lumon_scene_chunk_slot", 2)]
[ShaderStage("LumonSceneChunkSlotContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonSceneChunkSlotContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_chunk_slot.fsh")]
[ShaderAcceptGroup("LumonSceneChunkSlotContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonSceneChunkSlotContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonSceneSlotGenerationContract", "lumon_debug_view_lumon_scene_slot_generation", 2)]
[ShaderStage("LumonSceneSlotGenerationContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonSceneSlotGenerationContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_slot_generation.fsh")]
[ShaderAcceptGroup("LumonSceneSlotGenerationContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonSceneSlotGenerationContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonScenePageTableOccupancyContract", "lumon_debug_view_lumon_scene_page_table_occupancy", 2)]
[ShaderStage("LumonScenePageTableOccupancyContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonScenePageTableOccupancyContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_page_table_occupancy.fsh")]
[ShaderAcceptGroup("LumonScenePageTableOccupancyContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonScenePageTableOccupancyContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonSceneMaterialContract", "lumon_debug_view_lumon_scene_material", 2)]
[ShaderStage("LumonSceneMaterialContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonSceneMaterialContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_material.fsh")]
[ShaderAcceptGroup("LumonSceneMaterialContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonSceneMaterialContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonSceneMaterialAtlasAllContract", "lumon_debug_view_lumon_scene_material_atlas_all", 2)]
[ShaderStage("LumonSceneMaterialAtlasAllContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonSceneMaterialAtlasAllContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_material_atlas_all.fsh")]
[ShaderAcceptGroup("LumonSceneMaterialAtlasAllContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonSceneMaterialAtlasAllContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonSceneMaterialRoughnessContract", "lumon_debug_view_lumon_scene_material_roughness", 2)]
[ShaderStage("LumonSceneMaterialRoughnessContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonSceneMaterialRoughnessContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_material_roughness.fsh")]
[ShaderAcceptGroup("LumonSceneMaterialRoughnessContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonSceneMaterialRoughnessContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonSceneMaterialAtlasAllRoughnessContract", "lumon_debug_view_lumon_scene_material_atlas_all_roughness", 2)]
[ShaderStage("LumonSceneMaterialAtlasAllRoughnessContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonSceneMaterialAtlasAllRoughnessContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_material_atlas_all_roughness.fsh")]
[ShaderAcceptGroup("LumonSceneMaterialAtlasAllRoughnessContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonSceneMaterialAtlasAllRoughnessContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("LumonSceneMaterialAtlasAllNormalsContract", "lumon_debug_view_lumon_scene_material_atlas_all_normals", 2)]
[ShaderStage("LumonSceneMaterialAtlasAllNormalsContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("LumonSceneMaterialAtlasAllNormalsContract", ShaderStageKind.Fragment, "lumon_debug_view_lumon_scene_material_atlas_all_normals.fsh")]
[ShaderAcceptGroup("LumonSceneMaterialAtlasAllNormalsContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("LumonSceneMaterialAtlasAllNormalsContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("TraceSceneDdaDistanceL0Contract", "lumon_debug_view_trace_scene_dda_distance_l0", 2)]
[ShaderStage("TraceSceneDdaDistanceL0Contract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("TraceSceneDdaDistanceL0Contract", ShaderStageKind.Fragment, "lumon_debug_view_trace_scene_dda_distance_l0.fsh")]
[ShaderAcceptGroup("TraceSceneDdaDistanceL0Contract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("TraceSceneDdaDistanceL0Contract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("WorldProbeImportanceContract", "lumon_debug_view_world_probe_importance", 4)]
[ShaderStage("WorldProbeImportanceContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("WorldProbeImportanceContract", ShaderStageKind.Fragment, "lumon_debug_view_world_probe_importance.fsh")]
[ShaderAcceptGroup("WorldProbeImportanceContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("WorldProbeImportanceContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderAcceptGroup("WorldProbeImportanceContract", typeof(LumOnShaderGroups), "World")]
[ShaderAcceptGroup("WorldProbeImportanceContract", typeof(LumOnShaderGroups), "WorldGather")]
[ShaderUse("WorldProbeImportanceContract", ShaderStageKind.Fragment, nameof(WorldProbeBaseSpacing), SpecializationId = 11, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeImportanceContract", ShaderStageKind.Fragment, nameof(WorldProbeLevels), SpecializationId = 12, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeImportanceContract", ShaderStageKind.Fragment, nameof(WorldProbeResolution), SpecializationId = 14, When = "WorldProbeEnabled")]
[ShaderUse("WorldProbeImportanceContract", ShaderStageKind.Fragment, nameof(WorldProbeEnabled))]
[ShaderProgram("ProbeAtlasTraceOutcomeContract", "lumon_debug_view_probe_atlas_trace_outcome", 2)]
[ShaderStage("ProbeAtlasTraceOutcomeContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("ProbeAtlasTraceOutcomeContract", ShaderStageKind.Fragment, "lumon_debug_view_probe_atlas_trace_outcome.fsh")]
[ShaderAcceptGroup("ProbeAtlasTraceOutcomeContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("ProbeAtlasTraceOutcomeContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
[ShaderProgram("NearFieldGeometryContract", "lumon_debug_view_near_field_geometry", 2)]
[ShaderStage("NearFieldGeometryContract", ShaderStageKind.Vertex, "lumon_debug.vsh")]
[ShaderStage("NearFieldGeometryContract", ShaderStageKind.Fragment, "lumon_debug_view_near_field_geometry.fsh")]
[ShaderAcceptGroup("NearFieldGeometryContract", typeof(LumOnShaderGroups), "Visibility")]
[ShaderUse("NearFieldGeometryContract", ShaderStageKind.Fragment, nameof(DirectVisibility))]
public partial class LumOnDebugShaderProgram { }
