using System;
using System.Globalization;
using System.IO;
using System.Text;

namespace ShaderBuildTool.Generation;

/// <summary>Generates fixed 8x8 octahedral cell integrals using the real basis in lumon_sh9_common.glsl.</summary>
internal static class LumonOctahedralShWeights
{
    #region Spherical moment integration
    /// <summary>Decodes a UV coordinate in double precision, including the lower octahedron fold.</summary>
    private static double[] Direction(double u, double v)
    {
        double x = u * 2 - 1, y = v * 2 - 1, z = 1 - Math.Abs(x) - Math.Abs(y);
        if (z < 0) { double oldX = x; x = (1 - Math.Abs(y)) * (x < 0 ? -1 : 1); y = (1 - Math.Abs(oldX)) * (y < 0 ? -1 : 1); }
        double inverse = 1 / Math.Sqrt(x * x + y * y + z * z);
        return new[] { x * inverse, y * inverse, z * inverse };
    }

    /// <summary>Returns the oriented normal used by spherical triangle boundaries.</summary>
    private static double[] Cross(double[] a, double[] b) => new[] { a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0] };

    /// <summary>Returns the scalar product in double precision.</summary>
    private static double Dot(double[] a, double[] b) => a[0]*b[0]+a[1]*b[1]+a[2]*b[2];

    /// <summary>Accumulates solid angle, first moment and the row-major second moment using spherical boundary integrals.</summary>
    private static void Triangle(double[] a, double[] b, double[] c, double[] m)
    {
        double determinant = Dot(a, Cross(b, c));
        if (Math.Abs(determinant) < 1e-15) return;
        if (determinant < 0) { var swap = b; b = c; c = swap; determinant = -determinant; }
        double area = 2 * Math.Atan2(determinant, 1 + Dot(a,b) + Dot(b,c) + Dot(c,a));
        m[0] += area;
        for (int i = 0; i < 3; i++) m[4 + i*3 + i] += area / 3;
        var vertices = new[] { a, b, c };
        for (int edge = 0; edge < 3; edge++)
        {
            var start = vertices[edge]; var end = vertices[(edge+1)%3];
            var normal = Cross(start,end);
            double length = Math.Sqrt(Dot(normal,normal));
            if (length < 1e-15) continue;
            double angle = Math.Atan2(length,Dot(start,end));
            for (int i = 0; i < 3; i++) normal[i] /= length;
            // Boundary normals point inward. Integrating the spherical Laplacians
            // of n_i and n_i*n_j gives these exact first/second moments.
            var boundary = new double[3];
            for (int i = 0; i < 3; i++) { m[1+i] += normal[i]*angle/2; boundary[i] = (start[i]+end[i])*Math.Tan(angle/2); }
            for (int i = 0; i < 3; i++) for (int j = 0; j < 3; j++)
                m[4+i*3+j] += (normal[i]*boundary[j]+normal[j]*boundary[i])/6;
        }
    }

    #endregion

    #region Table generation
    /// <summary>Writes geometric SH cell integrals after verifying that the cells partition the sphere.</summary>
    public static void Generate(string shadersRoot)
    {
        string path = Path.Combine(shadersRoot, "includes", "lumon_octahedral_sh9_weights.glsl");
        var weights = new double[64][];
        var totals = new double[13];
        // Center fans follow every octahedron fold in the 8x8 grid, leaving great-circle
        // triangle boundaries whose spherical moments can be integrated exactly.
        for (int y = 0; y < 8; y++) for (int x = 0; x < 8; x++)
        {
            var center = Direction((x+.5)/8,(y+.5)/8);
            var corners = new[] { Direction(x/8.0,y/8.0), Direction((x+1)/8.0,y/8.0), Direction((x+1)/8.0,(y+1)/8.0), Direction(x/8.0,(y+1)/8.0) };
            var m = new double[13];
            for (int edge = 0; edge < 4; edge++) Triangle(center,corners[edge],corners[(edge+1)&3],m);
            for (int i = 0; i < m.Length; i++) totals[i] += m[i];
            weights[(y<<3)+x] = new[] { .282095*m[0], .488603*m[2], .488603*m[3], .488603*m[1],
                1.092548*m[5], 1.092548*m[9], .315392*(3*m[12]-m[0]), 1.092548*m[6], .546274*(m[4]-m[8]) };
        }
        for (int i = 0; i < totals.Length; i++)
        {
            double expected = i == 0 ? 4*Math.PI : i >= 4 && (i-4)%4 == 0 ? 4*Math.PI/3 : 0;
            if (Math.Abs(totals[i]-expected) > 1e-10) throw new InvalidOperationException("Spherical partition moment failed: " + i);
        }
        var text = new StringBuilder("// Generated by ShaderBuildTool/Generation/LumonOctahedralShWeights.cs. Do not hand edit.\n// Each row is the integral of the real SH9 basis over one octahedral texel.\n#ifndef LUMON_OCTAHEDRAL_SH9_WEIGHTS_GLSL\n#define LUMON_OCTAHEDRAL_SH9_WEIGHTS_GLSL\n");
        for (int group = 0; group < 3; group++)
        {
            int count = group == 2 ? 1 : 4;
            string type = count == 1 ? "float" : "vec4";
            text.Append("const "+type+" LUMON_OCT_SH"+group+"[64] = "+type+"[64](\n");
            for (int row = 0; row < 64; row++)
            {
                text.Append("    "); if (count != 1) text.Append("vec4(");
                for (int c = 0; c < count; c++)
                {
                    if (c != 0) text.Append(", ");
                    double value = weights[row][(group<<2)+c];
                    text.Append(Math.Abs(value) < 1e-14 ? "0.0" : value.ToString("0.0000000000",CultureInfo.InvariantCulture));
                }
                if (count != 1) text.Append(")"); text.Append(row == 63 ? "\n);\n" : ",\n");
            }
        }
        text.Append("#endif\n");
        // Publish a complete include atomically. Keep the temporary file outside the shader
        // input tree so concurrent builds never fingerprint or parse an incomplete table.
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        string temporary = Path.Combine(Directory.GetParent(shadersRoot)!.FullName, ".lumon-sh-" + Guid.NewGuid().ToString("N") + ".tmp");
        try
        {
            File.WriteAllText(temporary, text.ToString(), new UTF8Encoding(false));
            File.Move(temporary, path, overwrite: true);
        }
        finally { File.Delete(temporary); }
    }
    #endregion
}
